image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

shallow_clone: true              

matrix:
    fast_finish: false           

platform:
    - x86
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

install:
    # скрипт настройки среды и установки зависимостей:
    - call ci/appveyor/set-env.bat %TOOLCHAIN% %PLATFORM%
    #- call ci/appveyor/install.bat
    
build_script:
    # скрипт сборки проекта:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

artifacts:
    - path: <local-package-path>
      name: package_name

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: <encrypted-github-token>

    artifact: package_name
    force_update: true

    on:
        appveyor_repo_tag: true
